#!/usr/bin/env php
<?php
/**
 * XHRM is a comprehensive Human Resource Management (HRM) System that captures
 * all the essential functionalities required for any enterprise.
 * Copyright (C) 2006 XHRM Inc., http://www.orangehrm.com
 *
 * XHRM is free software: you can redistribute it and/or modify it under the terms of
 * the GNU General Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 *
 * XHRM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with XHRM.
 * If not, see <https://www.gnu.org/licenses/>.
 */

$pathToAutoload = realpath(__DIR__ . '/../src/vendor/autoload.php');

$errorMessage = "
Cannot find composer dependencies.
Run below command and try again;\n
$ cd %s
$ composer install -d src
";

if (!$pathToAutoload) {
    echo sprintf($errorMessage, realpath(__DIR__ . '/../'));
    exit(1);
}

use XHRM\Framework\Console\Console;
use XHRM\Framework\Http\Session\MemorySessionStorage;
use XHRM\Framework\Http\Session\Session;
use XHRM\Framework\ServiceContainer;
use XHRM\Framework\Services;
use XHRM\Installer\Command\InstallerCountryListCommand;
use XHRM\Installer\Command\InstallOnExistingDatabaseCommand;
use XHRM\Installer\Command\InstallOnNewDatabaseCommand;
use XHRM\Installer\Command\UpgradeCommand;
use XHRM\Installer\Framework\HttpKernel;

set_time_limit(0);

require_once $pathToAutoload;

$env = 'prod';
$debug = 'prod' !== $env;

$console = new Console();
new HttpKernel($env, $debug); // initializing kernel
$sessionStorage = new MemorySessionStorage();
ServiceContainer::getContainer()->set(Services::SESSION_STORAGE, $sessionStorage);
$session = new Session($sessionStorage);
$session->start();
ServiceContainer::getContainer()->set(Services::SESSION, $session);

$console->add(new InstallOnNewDatabaseCommand());
$console->add(new InstallOnExistingDatabaseCommand());
$console->add(new UpgradeCommand());
$console->add(new InstallerCountryListCommand());

$console->setName('XHRM Command Line Installer');
$console->setVersion('1.0.0');
$console->run();
